export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const SET_CUSTOMER_IDENTITY = 'SET_CUSTOMER_IDENTITY';
export const SET_CUSTOMER_NAME = 'SET_CUSTOMER_NAME';
export const SET_CUSTOMER_ADDRESS = 'SET_CUSTOMER_ADDRESS';
export const SET_CUSTOMER_TYPE = 'SET_CUSTOMER_TYPE';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
