GET http://localhost:5000


###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "thangdb1",
    "password": "123456"
}


###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "quang127",
    "password": "test"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "thangdb1",
    "password": "123456"
}

###
GET http://localhost:5000/api/rooms/allrooms

###
GET http://localhost:5000/api/rooms/635ea234dce841597e4fa833




