GET http://localhost:5000


###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "thangdb",
    "password": "123456"
}


###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "quang127",
    "password": "test"
}

